nvcodec: update example text to reflect HEVC
bytedeco/javacpp-presets pull request #1167
Opened 2022-04-11 09:55 UTC by bradh

The text says MPEG-1, but the capability being checked is HEVC.

2022-04-11 09:56 UTC, bradh commented
@devjeonghwan If you have an opportunity, can you take a look at this small patch?

2022-04-13 04:29 UTC, saudet commented
@devjeonghwan Does this look OK to you?

2022-04-14 13:12 UTC, devjeonghwan commented
@bradh
I missed something wrong!

The original sample intent was to "always succeed". So I wrote sample code that check "MPEG-1" codec support. (because all of nvidia graphic card is support MPEG-1)

[Video Decoder Capabilities Table](https://docs.nvidia.com/video-technologies/video-codec-sdk/nvdec-video-decoder-api-prog-guide/index.html#video-decoder-capabilities__table_o3x_fms_3lb)

Here is my suggest.
```java
// Query decoder capability 'MPEG-1' codec
{
    CUVIDDECODECAPS decodeCaps = new CUVIDDECODECAPS();
    decodeCaps.eCodecType(cudaVideoCodec_MPEG1);
    decodeCaps.eChromaFormat(cudaVideoChromaFormat_420);
    decodeCaps.nBitDepthMinus8(0);

    checkCudaApiCall("cuvidGetDecoderCaps", cuvidGetDecoderCaps(decodeCaps));

    System.out.printf("Decoder Capability MPEG-1 Codec\t : %s \r\n", (decodeCaps.bIsSupported() != 0));
}
```

2022-04-14 13:14 UTC, devjeonghwan requested changes

2022-04-14 13:14 UTC, devjeonghwan commented on nvcodec/README.md
>              decodeCaps.eCodecType(cudaVideoCodec_HEVC);
Change `cudaVideoCodec_HEVC` to `cudaVideoCodec_MPEG1`

2022-04-14 13:14 UTC, devjeonghwan commented on nvcodec/samples/simple/SampleEncodeDecode.java
>              decodeCaps.eCodecType(cudaVideoCodec_HEVC);
Change `cudaVideoCodec_HEVC` to `cudaVideoCodec_MPEG1`

2022-04-14 21:46 UTC, closed without merging

2022-04-14 23:12 UTC, bradh commented
> @bradh I missed something wrong!
> 
> The original sample intent was to "always succeed". So I wrote sample code that check "MPEG-1" codec support. (because all of nvidia graphic card is support MPEG-1)

OK. However having that code in the README.md might make the nvcodec capabilities look fairly limited. Would it be OK to have three (e.g. H.264/AVC - supported on all cards, H.265/HEVC - supported on more recent cards, and AV1 - supported on only the most recent GPUs)? The code should still run and always succeed on the first, but shows a wider range of capabilities.

Unrelated to that, is any cleanup on the context (`cuContext`) required (for the general case)?

Brad

2022-04-15 00:56 UTC, devjeonghwan commented
@bradh 

> OK. However having that code in the README.md might make the nvcodec capabilities look fairly limited. Would it be OK to have three (e.g. H.264/AVC - supported on all cards, H.265/HEVC - supported on more recent cards, and AV1 - supported on only the most recent GPUs)? The code should still run and always succeed on the first, but shows a wider range of capabilities.

Yeah, Sounds good! We can use`H.264` instead of `MPEG-1`.

> Unrelated to that, is any cleanup on the context (cuContext) required (for the general case)?

Yes, `Simple Sample` didn't care about resource cleanup. If necessary, we need to change it as below.

```java
int targetGpu = 0; // If you use NVIDIA GPU not '0', changing it.

CUctx_st cuContext = new CUctx_st();

checkCudaApiCall("cuInit", cuInit(0));
checkCudaApiCall("cuCtxCreate", cuCtxCreate(cuContext, 0, targetGpu));
try {
    // Check encoder max supported version
    {
        try (IntPointer version = new IntPointer(1)) {
            checkEncodeApiCall("NvEncodeAPIGetMaxSupportedVersion", NvEncodeAPIGetMaxSupportedVersion(version));

            System.out.printf("Encoder Max Supported Version\t : %d \r\n", version.get());
        }
    }

    // Query decoder capability 'MPEG-1' codec
    {
        try (CUVIDDECODECAPS decodeCaps = new CUVIDDECODECAPS()) {
            decodeCaps.eCodecType(cudaVideoCodec_MPEG1);
            decodeCaps.eChromaFormat(cudaVideoChromaFormat_420);
            decodeCaps.nBitDepthMinus8(0);

            checkCudaApiCall("cuvidGetDecoderCaps", cuvidGetDecoderCaps(decodeCaps));

            System.out.printf("Decoder Capability MPEG-1 Codec\t : %s \r\n", (decodeCaps.bIsSupported() != 0));
        }
    }
} finally {
    checkCudaApiCall("cuCtxDestroy", cuCtxDestroy(this.context));
}
```

(`nvcodec/samples/src/...` Samples contain resource cleanup.)